spring:
  datasource:
    url: jdbc:sqlserver://localhost;databaseName=master;encrypt=false
    username: sa
    password: Fsoft123!
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    database-platform: org.hibernate.dialect.SQLServerDialect
    show-sql: true
    hibernate:
      ddl-auto: update

  security:
    user:
      name: dat   # Thay đổi tên người dùng
      password: 12345   # Thay đổi mật khẩu

springdoc:
  api-docs:
    path: /api-docs
